import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from '@clerk/nextjs';
import { Nunito_Sans, Kanit } from 'next/font/google';

const kanit = Kanit({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "BitX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${kanit.className}`}>
          <Providers>
            <header className="fixed top-0 left-0 w-full">
              <Navbar />
            </header>
            <main className="content">
              {children}
            </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
